### ISSUE TITLE
Consolidate all new posts in a single email

### ISSUE THREAD

**Issue by maxim-devpronet** [wking/rss2email#3]
Is it possible to add an option to consolidate all new posts in a single email rather than sending each post as a separate email?

**Comment by martinmurciego** [comment]
You know, no opensource tool seems to have this of sending the newsletter every so often with all the new entries in an email instead of sending each new entry in a different email. As it is configured to send several entries of an rss feed in an email per week or twice a week. Where does that configuration go?

It is something that would be very useful to publish the solution. In my case I want to create a newsletter service so that you can subscribe to wordpress sites and send the new entries in an email once or twice a week. Mailtrain does not have it. It remains for me to see if phplist really has it as the well-known MailChimb has it.
